/* Exporting the TYPES object. */
export const TYPES = {
  SHOW_TOTAL: 'SHOW_TOTAL',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
};
